# Generated by Django 4.1.5 on 2023-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
